server:
  port: 8085
  servlet:
    context-path: /monitoring

spring:
  application:
    name: flowmaster-monitoring
  
  data:
    elasticsearch:
      repositories:
        enabled: true
      uris: http://localhost:9200
      connection-timeout: 10s
      socket-timeout: 30s
    redis:
      host: localhost
      port: 6379
      password: 
      database: 1
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  
  # Spring Cloud Sleuth配置
  sleuth:
    enabled: true
    zipkin:
      base-url: http://localhost:9411
    sampler:
      probability: 1.0

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,zipkin
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms

# 日志配置
logging:
  level:
    com.flowmaster.monitoring: DEBUG
    org.springframework.data.elasticsearch: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"

# 监控服务配置
monitoring:
  metrics:
    collection-interval: 30s
    retention-period: 7d
  logging:
    index-prefix: flowmaster
    retention-period: 30d
    batch-size: 1000
  tracing:
    sample-rate: 1.0
    retention-period: 3d
