server:
  port: 8083
  servlet:
    context-path: /workflow-service

spring:
  application:
    name: flowmaster-workflow-service
  
  profiles:
    active: dev
  
  cloud:
    nacos:
      discovery:
        enabled: false  # 禁用Nacos服务发现
      config:
        enabled: false
    config:
      enabled: false
      import-check:
        enabled: false
    compatibility-verifier:
      enabled: false

  main:
    allow-bean-definition-overriding: true
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:flowmaster123}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none  # 禁用JPA自动建表，让Flowable控制
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:flowmaster123}
      database: 2
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# Eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Flowable配置
flowable:
  # 数据库配置
  database-schema-update: true
  # 禁用自动配置，让Flowable完全控制数据库
  check-process-definitions: false
  # 禁用EventRegistry引擎
  eventregistry:
    enabled: false
  # 禁用IDM引擎
  idm:
    enabled: false
  
  # 流程引擎配置
  process:
    definition-cache-limit: 1
    definition-cache-limit-per-definition: 1
    enable-safe-xml: true
  
  # 任务配置
  task:
    enable-safe-xml: true
  
  # 历史配置
  history:
    level: full
  
  # 异步执行器配置
  async-executor:
    activate: true
    core-pool-size: 2
    max-pool-size: 10
    queue-capacity: 100
    keep-alive-seconds: 60

# 工作流配置
workflow:
  # 流程定义配置
  process-definition:
    auto-deploy: true
    deploy-path: classpath:processes/
    cache-size: 100
  
  # 任务配置
  task:
    default-assignee: system
    default-candidate-groups: users
    timeout-days: 7
  
  # 历史配置
  history:
    retention-days: 90
    cleanup-enabled: true
  
  # 通知配置
  notification:
    enabled: true
    email:
      enabled: true
      smtp-host: smtp.example.com
      smtp-port: 587
      username: ${EMAIL_USERNAME:}
      password: ${EMAIL_PASSWORD:}
    webhook:
      enabled: false
      url: ${WEBHOOK_URL:}

# 日志配置
logging:
  level:
    com.flowmaster.workflow: DEBUG
    org.flowable: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# 应用信息
info:
  app:
    name: FlowMaster Workflow Service
    description: FlowMaster工作流引擎服务
    version: 1.0.0-SNAPSHOT
    encoding: UTF-8
    java:
      version: ${java.version}

# Swagger配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true
